apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storage
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/artful-reef-468106-g6/regions/us-central1/disks/mongo-disk
    fsType: ext4